version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ssf_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sales}
      POSTGRES_USER: ${POSTGRES_USER:-sales_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sales_pass}
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: 